name: Integration tests

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

on:
  pull_request:
  workflow_dispatch:

jobs:
  integration-tests:
    name: Integration tests (multi-cloud)
    uses: canonical/operator-workflows/.github/workflows/integration_test.yaml@main
    secrets: inherit
    permissions:
      contents: read
      packages: write
    with:
      runs-on: "self-hosted-linux-amd64-noble-xlarge"
      use-canonical-k8s: true
      channel: "1.32-classic/stable"
      juju-channel: "3/stable"
      trivy-severity-config: CRITICAL
      modules: '["test_charm.py", "test_upgrade.py", "test_scaling.py"]'
      with-uv: true
