name: Integration tests

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

on:
  pull_request:
  workflow_dispatch:

jobs:
  # Ref: https://github.com/canonical/livepatch-k8s-operator/blob/b48995d02f549dca0be46dd15790b5985669d7fe/.github/workflows/integration_test.yaml#L51
  integration-tests:
    name: Integration tests (multi-cloud)
    runs-on: [self-hosted, linux, X64, jammy, xlarge]
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Install LXD
        uses: canonical/setup-lxd@v0.1.1
        with:
          channel: 6.1/stable
      - name: Setup operator environment
        uses: charmed-kubernetes/actions-operator@main
        with:
          channel: 1.29-strict/stable
          juju-channel: 3.5/stable
          provider: microk8s
          microk8s-group: snap_microk8s
          microk8s-addons: "ingress hostpath-storage dns rbac registry"
      - name: Bootstrap a controller on the LXD cloud
        run: |
          juju bootstrap localhost localhost-localhost
      # Make microk8s accessible by LXD.
      - name: Tweak microk8s API address
        run: |
          sudo microk8s.config > /tmp/client.config
          sudo cp /tmp/client.config /var/snap/microk8s/current/credentials/client.config
      - name: Add microk8s cloud to the LXD controller
        run: |
          /usr/bin/sudo -g snap_microk8s -E juju add-cloud microk8s --controller localhost-localhost --credential microk8s
      # Pack the charm ahead of tests to speed up the process.
      - name: Install Charmcraft
        run: sudo snap install charmcraft --classic
      - name: Build charm
        run: charmcraft pack --verbosity=trace
      - name: Install tox
        run: |
          python -m pip install tox
      - name: Run integration tests
        run: |
          tox -e integration
      - name: Dump logs
        if: failure()
        uses: canonical/charming-actions/dump-logs@main
