name: Integration tests

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

on:
  pull_request:
  workflow_dispatch:

jobs:
  integration-tests:
    name: Integration tests (multi-cloud)
    uses: canonical/operator-workflows/.github/workflows/integration_test.yaml@main
    secrets: inherit
    with:
      runs-on: "self-hosted-linux-amd64-noble-xlarge"
      provider: microk8s
