name: Publish Charm

on:
  push:
    branches:
      - main
    paths-ignore:
      - "bundle/**"
  workflow_dispatch:

run-name: Release charm by @${{ github.actor }}

jobs:
  upload-datahub-k8s:
    uses: canonical/operator-workflows/.github/workflows/publish_charm.yaml@main
    with:
      channel: "latest/edge"
      resource-mapping: '{"datahub-actions": "datahub-actions", "datahub-frontend": "datahub-frontend", "datahub-gms": "datahub-gms"}'
    secrets: inherit
